apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-valeria
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 19.0.0
    chart: redis
    helm:
      values: |
        image:
          tag: latest
        auth:
          enabled: false
        architecture: standalone
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default